"use client";
import { useEffect, useRef, useState } from "react";
import "./structured.css";
type Tab="Generate"|"Library"|"Voice"|"Approvals"|"Settings";
type Resource={id:string;type:string;title:string;content?:string;url?:string;filename?:string};
type Draft={id:string;caption:string;proposed_at:number|null;content_type:string;tone:string;cta:string};
const H={"content-type":"application/json","x-workspace-id":"ws_riverlight"};
async function json(r:Response){const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw new Error(t.slice(0,300)||`Server ${r.status}`)}if(!r.ok)throw new Error(d.error||`Server ${r.status}`);return d}

export default function Home(){
 const[tab,setTab]=useState<Tab>("Generate"),[version,setVersion]=useState("0.4.0"),[drafts,setDrafts]=useState<Draft[]>([]),[resources,setResources]=useState<Resource[]>([]),[error,setError]=useState("");
 const[settings,setSettings]=useState({tonePrompt:"",organizationInfo:"",llmBaseUrl:"http://host.docker.internal:1234",llmModel:"qwen",temperature:.4,maxTokens:2000});
 async function reload(){try{await json(await fetch("/api/bootstrap",{method:"POST",headers:H}));const[a,b,c,v]=await Promise.all([fetch("/api/approvals",{headers:H}),fetch("/api/resources",{headers:H}),fetch("/api/settings",{headers:H}),fetch("/api/version")]);setDrafts((await json(a)).approvals||[]);setResources((await json(b)).resources||[]);const s=(await json(c)).settings;if(s)setSettings({tonePrompt:s.tone_prompt||"",organizationInfo:s.organization_info||"",llmBaseUrl:s.llm_base_url,llmModel:s.llm_model,temperature:s.temperature,maxTokens:s.max_tokens});setVersion((await json(v)).version)}catch(e){setError(e instanceof Error?e.message:"Unable to load")}}
 useEffect(()=>{reload()},[]);
 return <main><header className="top"><div className="logo">SC</div><div><h1>Social Cockpit</h1><p>Structured post generator <b>v{version}</b></p></div><nav>{(["Generate","Library","Voice","Approvals","Settings"] as Tab[]).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}{x==="Approvals"&&drafts.length?<em>{drafts.length}</em>:null}</button>)}</nav></header>{error&&<div className="global-error">{error}<button onClick={()=>setError("")}>×</button></div>}<section className="page">{tab==="Generate"&&<Generate resources={resources} reload={reload} fail={setError}/>} {tab==="Library"&&<Library items={resources} reload={reload} fail={setError}/>} {tab==="Voice"&&<Voice s={settings} set={setSettings} fail={setError}/>} {tab==="Approvals"&&<Approvals items={drafts} reload={reload} fail={setError}/>} {tab==="Settings"&&<Settings s={settings} set={setSettings} fail={setError}/>}</section></main>
}

function Generate({resources,reload,fail}:{resources:Resource[];reload:()=>Promise<void>;fail:(x:string)=>void}){
 const events=resources.filter(x=>x.type==="event"),[eventId,setEventId]=useState(""),[topic,setTopic]=useState(""),[tone,setTone]=useState("Saved voice"),[count,setCount]=useState(3),[start,setStart]=useState(""),[end,setEnd]=useState(""),[notes,setNotes]=useState(""),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[done,setDone]=useState("");
 const chosen=events.find(x=>x.id===eventId);async function go(){const subject=chosen?`${chosen.title}\n${chosen.content||""}\n${chosen.url||""}`:topic;if(!subject||!start||!end){fail("Choose an event or topic and a date range");return}setBusy(true);fail("");try{const d=await json(await fetch("/api/generate",{method:"POST",headers:H,body:JSON.stringify({topic:subject,tone,count,startDate:start,endDate:end,instructions:notes,resourceIds:selected})}));setDone(`${d.created} drafts created and sent to Approvals.`);await reload()}catch(e){fail(e instanceof Error?e.message:"Generation failed")}finally{setBusy(false)}}
 return <><Title name="Generate posts" sub="Choose the inputs. Qwen only assembles and writes the final captions."/><div className="generator-grid"><article className="card form"><label>Event<select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">No saved event</option>{events.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label>{!eventId&&<label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="What is the post about?"/></label>}<div className="form-row"><label>Posts<input type="number" min="1" max="30" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>Tone<select value={tone} onChange={e=>setTone(e.target.value)}><option>Saved voice</option><option>Conversational</option><option>Informational</option><option>Excited</option><option>Urgent</option><option>Warm</option><option>Funny</option></select></label></div><div className="form-row"><label>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End date<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label>Anything to add? <small>Optional</small><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Mention registration closes Friday, avoid emojis, include the address…"/></label><button onClick={go} disabled={busy}>{busy?"Writing posts…":"Generate drafts"}</button>{done&&<p className="success">{done}</p>}</article><article className="card"><h3>Use from library</h3><p className="hint">Only checked items are sent to Qwen.</p><div className="resource-checks">{resources.filter(x=>x.id!==eventId).map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/><span><b>{x.title}</b><small>{x.type} · {x.filename||x.url||"saved info"}</small></span></label>)}{!resources.length&&<Empty text="Add events, links, or flyers in Library."/>}</div></article></div></>
}

function Library({items,reload,fail}:{items:Resource[];reload:()=>Promise<void>;fail:(x:string)=>void}){const[type,setType]=useState("event"),[title,setTitle]=useState(""),[url,setUrl]=useState(""),[content,setContent]=useState("");const file=useRef<HTMLInputElement>(null);async function add(){try{await json(await fetch("/api/resources",{method:"POST",headers:H,body:JSON.stringify({type,title,url,content})}));setTitle("");setUrl("");setContent("");await reload()}catch(e){fail(e instanceof Error?e.message:"Save failed")}}async function upload(f?:File){if(!f)return;const form=new FormData();form.set("file",f);try{await json(await fetch("/api/resources",{method:"POST",headers:{"x-workspace-id":"ws_riverlight"},body:form}));await reload()}catch(e){fail(e instanceof Error?e.message:"Upload failed")}}async function remove(id:string){await json(await fetch(`/api/resources?id=${id}`,{method:"DELETE",headers:H}));await reload()}return <><Title name="Library" sub="Store events, reusable information, links, images, and flyers."/><div className="two"><article className="card form"><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="event">Event</option><option value="link">Link</option><option value="note">Reusable information</option></select></label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Link (optional)"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Event details, facts, address, registration info…"/><button onClick={add}>Save</button><hr/><input ref={file} type="file" accept="image/*,.pdf" onChange={e=>upload(e.target.files?.[0])}/><button className="secondary" onClick={()=>file.current?.click()}>Upload image, flyer, or PDF</button></article><div className="items">{items.map(x=><article className="item" key={x.id}><span>{x.type}</span><h3>{x.title}</h3><p>{x.content||x.filename||x.url}</p><button onClick={()=>remove(x.id)}>Remove</button></article>)}</div></div></>}
function Voice({s,set,fail}:{s:any;set:(x:any)=>void;fail:(x:string)=>void}){return <><Title name="Voice" sub="Set your default writing style once."/><article className="card form settings"><label>Tone prompt<textarea className="large" value={s.tonePrompt} onChange={e=>set({...s,tonePrompt:e.target.value})}/></label><label>Organization information<textarea className="large" value={s.organizationInfo} onChange={e=>set({...s,organizationInfo:e.target.value})}/></label><button onClick={()=>save(s,fail)}>Save voice</button></article></>}
function Approvals({items,reload,fail}:{items:Draft[];reload:()=>Promise<void>;fail:(x:string)=>void}){async function decide(id:string,decision:string){try{await json(await fetch("/api/approvals",{method:"PATCH",headers:H,body:JSON.stringify({postId:id,decision})}));await reload()}catch(e){fail(e instanceof Error?e.message:"Review failed")}}return <><Title name="Approvals" sub="Review every finished caption."/><div className="approval-grid">{items.length?items.map(x=><article className="draft" key={x.id}><header><span>{x.content_type}</span><time>{x.proposed_at?new Date(x.proposed_at).toLocaleDateString():"No date"}</time></header><p>{x.caption}</p><footer><button onClick={()=>decide(x.id,"rejected")}>Reject</button><button className="approve" onClick={()=>decide(x.id,"approved")}>Approve</button></footer></article>):<Empty text="Nothing is waiting."/>}</div></>}
function Settings({s,set,fail}:{s:any;set:(x:any)=>void;fail:(x:string)=>void}){return <><Title name="Settings" sub="Connect Qwen through LM Studio."/><article className="card form settings"><label>LM Studio URL<input value={s.llmBaseUrl} onChange={e=>set({...s,llmBaseUrl:e.target.value})}/></label><label>Model ID<input value={s.llmModel} onChange={e=>set({...s,llmModel:e.target.value})}/></label><div className="form-row"><label>Temperature<input type="number" step=".1" value={s.temperature} onChange={e=>set({...s,temperature:Number(e.target.value)})}/></label><label>Max tokens<input type="number" value={s.maxTokens} onChange={e=>set({...s,maxTokens:Number(e.target.value)})}/></label></div><button onClick={()=>save(s,fail)}>Save settings</button></article></>}
async function save(s:any,fail:(x:string)=>void){try{await json(await fetch("/api/settings",{method:"PUT",headers:H,body:JSON.stringify(s)}))}catch(e){fail(e instanceof Error?e.message:"Save failed")}}function Title({name,sub}:{name:string;sub:string}){return <div className="title"><span>RIVERLIGHT HQ</span><h2>{name}</h2><p>{sub}</p></div>}function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
