import { env } from "cloudflare:workers";
import { assertToolCall, type ToolContext } from "./tools";

export async function executeTool(name:string,args:Record<string,unknown>,context:ToolContext){
  assertToolCall(name,args,context); const db=env.DB; const ws=context.workspaceId;
  if(name==="get_upcoming_events") return {events:(await db.prepare("SELECT * FROM events WHERE workspace_id=? AND starts_at>=? ORDER BY starts_at LIMIT 50").bind(ws,Date.now()).all()).results};
  if(name==="get_content_calendar") return {posts:(await db.prepare("SELECT p.*,a.platform,a.name account_name FROM posts p JOIN social_accounts a ON a.id=p.account_id WHERE p.workspace_id=? AND COALESCE(p.proposed_at,p.scheduled_at,p.published_at) BETWEEN ? AND ? ORDER BY COALESCE(p.proposed_at,p.scheduled_at,p.published_at)").bind(ws,new Date(String(args.start)).getTime(),new Date(String(args.end)).getTime()).all()).results};
  if(name==="get_pending_approvals") {const rows=(await db.prepare("SELECT p.id,p.caption,p.proposed_at,p.content_type FROM approvals a JOIN posts p ON p.id=a.post_id WHERE a.workspace_id=? AND a.status='pending'").bind(ws).all()).results;return {count:rows.length,drafts:rows}}
  if(name==="get_performance_insights") return {insights:(await db.prepare("SELECT finding,evidence,sample_size,confidence,platform,generated_at FROM performance_insights WHERE workspace_id=? AND (? IS NULL OR platform=?) ORDER BY generated_at DESC LIMIT 20").bind(ws,args.platform||null,args.platform||null).all()).results,dateRange:`${args.days||90} days`};
  if(name==="find_content_gaps") {const posts=(await db.prepare("SELECT proposed_at FROM posts WHERE workspace_id=? AND proposed_at BETWEEN ? AND ?").bind(ws,new Date(String(args.start)).getTime(),new Date(String(args.end)).getTime()).all()).results;return {scheduledPosts:posts,gaps:posts.length<3?["Fewer than three posts are planned in this range"]:[]}}
  if(name==="create_post_drafts") {const requested=Array.isArray(args.posts)?args.posts.slice(0,12) as Array<Record<string,unknown>>:[];if(!requested.length)throw new Error("At least one complete post is required");const account=await db.prepare("SELECT id FROM social_accounts WHERE workspace_id=? ORDER BY id LIMIT 1").bind(ws).first<{id:string}>();if(!account)throw new Error("No social account exists in this workspace");const now=Date.now();const statements=[];const ids=[];for(const post of requested){if(typeof post.caption!=="string"||!post.caption.trim())throw new Error("Every draft needs a caption");const id=crypto.randomUUID();ids.push(id);const proposed=post.proposedAt?new Date(String(post.proposedAt)).getTime():null;if(proposed!==null&&!Number.isFinite(proposed))throw new Error("Invalid proposed date");statements.push(db.prepare("INSERT INTO posts (id,workspace_id,account_id,campaign_id,status,proposed_at,caption,content_type,tone,cta,media_type,historical,created_at,updated_at) VALUES (?,?,?,?,'draft',?,?,?,?,?,'Text only',0,?,?)").bind(id,ws,account.id,args.campaignId||null,proposed,post.caption,String(post.contentType||"Announcement"),String(post.tone||"Conversational"),String(post.cta||"Learn more"),now,now));statements.push(db.prepare("INSERT INTO approvals (id,workspace_id,post_id,status,requested_by,requested_at) VALUES (?,?,?,'pending','ai',?)").bind(crypto.randomUUID(),ws,id,now))}await db.batch(statements);return {created:requested.length,ids,status:"pending_approval",publishingAttempted:false}}
  if(name==="update_post_draft"){const result=await db.prepare("UPDATE posts SET caption=?,updated_at=? WHERE id=? AND workspace_id=? AND status='draft'").bind(args.caption,Date.now(),args.postId,ws).run();return {id:args.postId,updated:result.meta.changes===1,status:"pending_approval"}}
  if(name==="reschedule_post_draft"){const time=new Date(String(args.proposedAt)).getTime();if(!Number.isFinite(time))throw new Error("Invalid proposedAt");const result=await db.prepare("UPDATE posts SET proposed_at=?,updated_at=? WHERE id=? AND workspace_id=? AND status='draft'").bind(time,Date.now(),args.postId,ws).run();return {id:args.postId,updated:result.meta.changes===1,status:"pending_approval",scheduled:false}}
  throw new Error("Tool is not implemented");
}
