import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const workspaces = sqliteTable("workspaces", { id: text("id").primaryKey(), name: text("name").notNull(), createdAt: integer("created_at").notNull() });
export const accounts = sqliteTable("social_accounts", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), platform: text("platform").notNull(), name: text("name").notNull(), followers: integer("followers") });
export const campaigns = sqliteTable("campaigns", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), name: text("name").notNull(), startsAt: integer("starts_at"), endsAt: integer("ends_at") });
export const posts = sqliteTable("posts", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), accountId: text("account_id").notNull(), campaignId: text("campaign_id"), providerPostId: text("provider_post_id"), publishedAt: integer("published_at").notNull(), caption: text("caption"), permalink: text("permalink"), contentType: text("content_type"), tone: text("tone"), cta: text("cta"), mediaType: text("media_type"), historical: integer("historical",{mode:"boolean"}).notNull().default(false) }, t => [uniqueIndex("uq_posts_account_provider").on(t.accountId,t.providerPostId)]);
export const snapshots = sqliteTable("analytics_snapshots", { id: text("id").primaryKey(), postId: text("post_id").notNull(), provider: text("provider").notNull(), capturedAt: integer("captured_at").notNull(), impressions: integer("impressions"), reach: integer("reach"), engagement: integer("engagement"), engagementRate: real("engagement_rate"), rawMetrics: text("raw_metrics",{mode:"json"}), sourceRecordHash: text("source_record_hash") }, t => [uniqueIndex("uq_snapshot_source_hash").on(t.sourceRecordHash)]);
export const imports = sqliteTable("analytics_imports", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), provider: text("provider").notNull(), filename: text("filename").notNull(), objectKey: text("object_key").notNull(), status: text("status").notNull(), mapping: text("mapping",{mode:"json"}), createdAt: integer("created_at").notNull() });
export const insights = sqliteTable("performance_insights", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), accountId: text("account_id"), platform: text("platform"), finding: text("finding").notNull(), evidence: text("evidence",{mode:"json"}).notNull(), sampleSize: integer("sample_size").notNull(), confidence: text("confidence").notNull(), generatedAt: integer("generated_at").notNull() });
