import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const workspaces = sqliteTable("workspaces", { id: text("id").primaryKey(), name: text("name").notNull(), createdAt: integer("created_at").notNull() });
export const accounts = sqliteTable("social_accounts", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), platform: text("platform").notNull(), name: text("name").notNull(), followers: integer("followers") });
export const campaigns = sqliteTable("campaigns", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), name: text("name").notNull(), startsAt: integer("starts_at"), endsAt: integer("ends_at") });
export const events = sqliteTable("events", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), campaignId: text("campaign_id"), name: text("name").notNull(), description: text("description"), location: text("location"), startsAt: integer("starts_at").notNull(), endsAt: integer("ends_at"), url: text("url"), createdAt: integer("created_at").notNull() }, t => [index("idx_events_workspace_start").on(t.workspaceId,t.startsAt)]);
export const resources = sqliteTable("resources", { id:text("id").primaryKey(), workspaceId:text("workspace_id").notNull(), type:text("type").notNull(), title:text("title").notNull(), content:text("content"), url:text("url"), objectKey:text("object_key"), filename:text("filename"), mimeType:text("mime_type"), createdAt:integer("created_at").notNull() }, t=>[index("idx_resources_workspace_type").on(t.workspaceId,t.type)]);
export const workspaceSettings = sqliteTable("workspace_settings", { workspaceId:text("workspace_id").primaryKey(), tonePrompt:text("tone_prompt").notNull().default(""), organizationInfo:text("organization_info").notNull().default(""), llmBaseUrl:text("llm_base_url").notNull().default("http://host.docker.internal:1234"), llmModel:text("llm_model").notNull().default("qwen"), temperature:real("temperature").notNull().default(.4), maxTokens:integer("max_tokens").notNull().default(2000), updatedAt:integer("updated_at").notNull() });
export const posts = sqliteTable("posts", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), accountId: text("account_id").notNull(), campaignId: text("campaign_id"), eventId: text("event_id"), providerPostId: text("provider_post_id"), status: text("status").notNull().default("draft"), proposedAt: integer("proposed_at"), scheduledAt: integer("scheduled_at"), publishedAt: integer("published_at"), caption: text("caption"), permalink: text("permalink"), contentType: text("content_type"), tone: text("tone"), cta: text("cta"), mediaType: text("media_type"), historical: integer("historical",{mode:"boolean"}).notNull().default(false), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() }, t => [uniqueIndex("uq_posts_account_provider").on(t.accountId,t.providerPostId), index("idx_posts_workspace_status_time").on(t.workspaceId,t.status,t.proposedAt)]);
export const snapshots = sqliteTable("analytics_snapshots", { id: text("id").primaryKey(), postId: text("post_id").notNull(), provider: text("provider").notNull(), capturedAt: integer("captured_at").notNull(), impressions: integer("impressions"), reach: integer("reach"), engagement: integer("engagement"), engagementRate: real("engagement_rate"), rawMetrics: text("raw_metrics",{mode:"json"}), sourceRecordHash: text("source_record_hash") }, t => [uniqueIndex("uq_snapshot_source_hash").on(t.sourceRecordHash)]);
export const imports = sqliteTable("analytics_imports", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), provider: text("provider").notNull(), filename: text("filename").notNull(), objectKey: text("object_key").notNull(), status: text("status").notNull(), mapping: text("mapping",{mode:"json"}), createdAt: integer("created_at").notNull() });
export const insights = sqliteTable("performance_insights", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), accountId: text("account_id"), platform: text("platform"), finding: text("finding").notNull(), evidence: text("evidence",{mode:"json"}).notNull(), sampleSize: integer("sample_size").notNull(), confidence: text("confidence").notNull(), generatedAt: integer("generated_at").notNull() });
export const aiProviderConfigs = sqliteTable("ai_provider_configs", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), providerName: text("provider_name").notNull(), baseUrl: text("base_url").notNull(), model: text("model").notNull(), temperature: real("temperature").notNull().default(.4), maxTokens: integer("max_tokens").notNull().default(1200), systemInstructions: text("system_instructions"), encryptedSecretRef: text("encrypted_secret_ref"), enabled: integer("enabled",{mode:"boolean"}).notNull().default(true) });
export const aiPreferences = sqliteTable("ai_preferences", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), category: text("category").notNull(), preference: text("preference").notNull(), evidenceCount: integer("evidence_count").notNull().default(0), confidence: text("confidence").notNull(), editable: integer("editable",{mode:"boolean"}).notNull().default(true), updatedAt: integer("updated_at").notNull() });
export const aiActivity = sqliteTable("ai_activity", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), userRequest: text("user_request").notNull(), provider: text("provider"), model: text("model"), status: text("status").notNull(), createdAt: integer("created_at").notNull(), error: text("error") });
export const aiToolCalls = sqliteTable("ai_tool_calls", { id: text("id").primaryKey(), activityId: text("activity_id").notNull(), workspaceId: text("workspace_id").notNull(), toolName: text("tool_name").notNull(), actionKind: text("action_kind").notNull(), arguments: text("arguments",{mode:"json"}).notNull(), resultSummary: text("result_summary",{mode:"json"}), createdAt: integer("created_at").notNull() });
export const approvals = sqliteTable("approvals", { id: text("id").primaryKey(), workspaceId: text("workspace_id").notNull(), postId: text("post_id").notNull(), status: text("status").notNull().default("pending"), requestedBy: text("requested_by").notNull(), requestedAt: integer("requested_at").notNull(), decidedAt: integer("decided_at"), decidedBy: text("decided_by"), note: text("note") }, t => [uniqueIndex("uq_approvals_post").on(t.postId), index("idx_approvals_workspace_status").on(t.workspaceId,t.status)]);
