import { env } from "cloudflare:workers";
import { jsonError, requireWorkspace } from "../../../lib/workspace";

type Generated={caption?:unknown;contentType?:unknown;cta?:unknown};
export async function POST(request:Request){try{
  const ws=requireWorkspace(request);const b=await request.json() as Record<string,unknown>;
  const count=Math.max(1,Math.min(30,Number(b.count)||1));const topic=String(b.topic||"").trim();if(!topic)return Response.json({error:"Choose an event or enter a topic"},{status:400});
  const start=new Date(String(b.startDate||""));const end=new Date(String(b.endDate||b.startDate||""));if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<start)return Response.json({error:"Choose a valid date range"},{status:400});
  const s=await env.DB.prepare("SELECT * FROM workspace_settings WHERE workspace_id=?").bind(ws).first<Record<string,unknown>>();const ids=Array.isArray(b.resourceIds)?b.resourceIds.filter(x=>typeof x==="string").slice(0,20):[];let selected:unknown[]=[];
  if(ids.length){const marks=ids.map(()=>"?").join(",");selected=(await env.DB.prepare(`SELECT type,title,content,url,filename FROM resources WHERE workspace_id=? AND id IN (${marks})`).bind(ws,...ids).all()).results}
  const base=String(s?.llm_base_url||process.env.LLM_BASE_URL||"").replace(/\/$/,"").replace(/\/v1$/i,"");const model=String(s?.llm_model||process.env.LLM_MODEL||"");if(!base||!model)return Response.json({error:"Configure LM Studio in Settings"},{status:503});
  const tone=String(b.tone||"")==="Saved voice"?String(s?.tone_prompt||"Conversational"):String(b.tone||"Conversational");
  const payload={model,temperature:Number(s?.temperature??.4),max_tokens:Number(s?.max_tokens??2000),response_format:{type:"json_object"},messages:[{role:"system",content:"Write social media captions. Return valid JSON only: {\"posts\":[{\"caption\":\"...\",\"contentType\":\"Announcement\",\"cta\":\"Learn more\"}]}. Return exactly the requested number. Each caption must be complete and distinct. Do not include dates in captions unless relevant. No markdown or commentary."},{role:"user",content:JSON.stringify({numberOfPosts:count,topic,tone,additionalInstructions:String(b.instructions||""),organizationInfo:String(s?.organization_info||""),selectedResources:selected})}]};
  const response=await fetch(`${base}/v1/chat/completions`,{method:"POST",headers:{"content-type":"application/json",...(process.env.LLM_API_KEY?{authorization:`Bearer ${process.env.LLM_API_KEY}`}:{})},body:JSON.stringify(payload)});const raw=await response.text();if(!response.ok)throw new Error(`LM Studio returned ${response.status}: ${raw.slice(0,300)}`);let outer:any;try{outer=JSON.parse(raw)}catch{throw new Error(`LM Studio returned non-JSON: ${raw.slice(0,300)}`)}const content=outer.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("LM Studio returned no content");let parsed:any;try{parsed=JSON.parse(content.replace(/^```(?:json)?\s*|\s*```$/g,""))}catch{throw new Error(`Qwen did not return valid JSON: ${content.slice(0,300)}`)}const posts=(Array.isArray(parsed.posts)?parsed.posts:[]).slice(0,count) as Generated[];if(posts.length!==count)throw new Error(`Qwen returned ${posts.length} posts instead of ${count}`);
  const account=await env.DB.prepare("SELECT id FROM social_accounts WHERE workspace_id=? ORDER BY id LIMIT 1").bind(ws).first<{id:string}>();if(!account)throw new Error("No account exists");const now=Date.now(),span=end.getTime()-start.getTime(),statements=[],created=[];
  for(let i=0;i<posts.length;i++){const p=posts[i];if(typeof p.caption!=="string"||!p.caption.trim())throw new Error("Qwen returned an empty caption");const id=crypto.randomUUID();const at=start.getTime()+(posts.length===1?0:Math.round(span*i/(posts.length-1)));created.push({id,caption:p.caption,proposedAt:at});statements.push(env.DB.prepare("INSERT INTO posts (id,workspace_id,account_id,status,proposed_at,caption,content_type,tone,cta,media_type,historical,created_at,updated_at) VALUES (?,?,?,'draft',?,?,?,?,?,'Text only',0,?,?)").bind(id,ws,account.id,at,p.caption,String(p.contentType||"Announcement"),String(b.tone||"Conversational"),String(p.cta||"None"),now,now));statements.push(env.DB.prepare("INSERT INTO approvals (id,workspace_id,post_id,status,requested_by,requested_at) VALUES (?,?,?,'pending','generator',?)").bind(crypto.randomUUID(),ws,id,now))}await env.DB.batch(statements);return Response.json({created:created.length,posts:created});
}catch(e){return jsonError(e)}}
